Repository Lf-Network/oss-leaderboard, pull requests merged in 2020-10, with the labels that each got.

#23 HTML generation and deployment
  .editorconfig
  .github/workflows/main.yml
  final_html_output.py
  main.py
  style.css
Labels: ci

#26 Revamp of design aspect of the table with responsiveness table
  Makefile
  README.md
  assets/LF_Opensource.svg
  assets/Leader_icon.svg
  assets/bg.png
  assets/index.html
  assets/style.css
  final_html_output.py
  style.css
Labels: design, ux

#29 Update the score weights of all contribution types
  leaderboard/constants/contribTypes.py
  leaderboard/constants/scoreWeights.py
  leaderboard/utils/final_score_table.py
Labels: enhancement
